"""add iban

Revision ID: bb47ae902b92
Revises: e7db533af9b4
Create Date: 2022-07-18 21:01:36.773436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb47ae902b92'
down_revision = 'e7db533af9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('approvers', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('complainers', sa.Column('iban', sa.String(length=22), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complainers', 'iban')
    op.drop_column('approvers', 'iban')
    op.drop_column('admins', 'iban')
    # ### end Alembic commands ###
